spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jooq_template?autoReconnect=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
server:
  port: 8080